version: 0.2

phases:
  install:
    commands:
      - pip install -r requirements.txt
  pre_build:
    commands:
      - pytest --version
  build:
    commands:
      - echo Running tests...
      - pytest
  post_build:
    commands:
      - echo Build completed successfully.